# Site settings
title: Delegado An&ocirc;nimo
email: delegadoanonimopodcast@gmail.com
description: ""
baseurl: "http://delegadoanonimo.github.io"
url: ""
twitter_username: DelegadoAnonimo
github_username:  DelegadoAnonimo
facebook_username:  DelegadoAnonimo

# Build settings
encoding: UTF-8
markdown: kramdown
highlighter: false
permalink: pretty
paginate: 5
exclude: ["node_modules"]
