# Site settings
title: Delegado Anônimo
email: delegadoanonimopodcast@gmail.com
baseurl: "http://delegadoanonimo.github.io"
# baseurl: ""
url: ""
twitter_username: DelegadoAnonimo
github_username:  DelegadoAnonimo
facebook_username:  DelegadoAnonimo

# Build settings
encoding: UTF-8
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
exclude: ["node_modules"]